---
title: "TP 1: Análisis Exploratorio e Introducción a Regresión lineal"
output: html_notebook
---

Datos provistos por [Properati Argentina](https://www.properati.com.ar)

**Fecha y hora de entrega**: 5 de octubre de 2020 a las 9 a.m

**Fecha y hora de devolucion general**: 10 de octubre de 2020 a las 9 a.m

## INSTRUCCIONES

Deberán realizar el trabajo en un **RNotebook** y entregarlo en formato R Notebook o HTML

El **RNotebook** debe:

* Tener el siguiente nombre: eea2020_tp1_(apellido)_(nombre)
* Mostrar todo el código que escriban. NO USAR `echo=FALSE`
* Ser ordenado de acuerdo a las consignas propuestas

Una vez terminado el notebook deberán enviarlo por mail a eea.uba@gmail.com

## CRITERIOS DE EVALUACION

* Explicar los procedimientos y decisiones en el texto
* Comentar el código
* Llegar a los resultados esperados
* Recomendamos fuertemente usar las funciones de `tidyverse`

En caso que los resultados no sean los esperados y no logremos identificar las fuentes de error podemos pedirles que nos compartan el archivo .Rmd y ciertas bases de datos que vayan generando.

## CONSIGNAS

El objetivo general es poder crear un modelo lineal simple para explicar el precio de venta de las propiedades en Capital Federal reportadas por la empresa Properati. Para ello es necesario realizar analisis exploratorios, limpieza del dataset y realizar los modelos.
Vamos a utilizar datos del 2019 para no incorporar comportamientos atípicos ocasionados por la pandemia del COVID-19.

1) **Preparación de los datos (I)**
    a) Leer el archivo *ar_properties.csv* y mostrar su estructura
    b) Quedarse con aquellos registros que:
        i) Pertenecen a Argentina y Capital Federal
        ii) Cuyo precio esta en dólares (USD)
        iii) El tipo de propiedad sea: Departamento, PH o Casa
        iv) El tipo de operacion sea Venta
    c) Seleccionar las variables **id**, **l3**, **rooms**, **bedrooms**, **bathrooms**, **surface_total**, **surface_covered**, **price** y **property_type**.
  
Deberian llegar a un dataset con 61.905 observaciones y 9 variables.
 
2) **Análisis exploratorios (I)**
    a) Obtener la cantidad de valores únicos y de valores faltantes (NAs) para cada una de estas variables.
    b) Obtener la matriz de correlaciones para las variables numéricas. Pista: usen 'complete.obs' para poder omitir los valores faltantes. 
    c) Grafique la matriz de correlaciones usando la librería `corrr`.
    d) ¿Cómo es la correlación entre las variables *surface_total* y *surface_covered*? ¿Y la correlación entre *rooms* y *bathrooms*?
    e) ¿Cómo es la correlación de la variable a explicar, **price**, con el resto de las variables?
    
3) **Limpieza de datos**
    a) En el punto 2 deberían haber encontrado que la variable **bedrooms** presenta una alta proporción de valores faltantes y que presenta una fuerte correlación con la variable **rooms**. Por lo tanto, vamos a eliminarla.
    b) Eliminar todos los registros que presentan valores faltantes.
    c) Eliminar aquellos registros en los cuales la superficie total es menor a la superficie cubierta
  
Deberían llegar a un dataset con 50.828 observaciones y 8 variables.
  
4) **Análisis exploratorios (II)**
    a) Crear una nueva variable **precio_en_miles** que sea la variable *price* divida por 1000. Obtener estadísticas descriptivas para esta nueva variable (cuartiles, promedio, mínimo y máximo) y realizar un histograma de la misma.
    b) Obtener las mismas estadísticas descriptivas de la nueva variable **precio_en_miles** para cada tipo de propiedad y realizar boxplots paralelos de la variable según tipo de propiedad. ¿Qué diferencias encuentran entre los tipos de propiedad?
    c) Realizar un gráfico con la función `ggpairs` de las variables numéricas (sin abrir por tipo de propiedad). Comenten los aspectos principales que observan en el gráfico

5) **Outliers**
    a) Graficar un scatterplot de la variable **precio_en_miles** y **superficie_total**. ¿Detectan alguna anomalía?
    b) Eliminar los outliers univariados de las variables **precio_en_miles**, **rooms** y **surface_total**. Utilizar y fundamentar el o los criterio/s y métodos que consideren adecuados.
    
6) **Análisis exploratorios (III)**
    a) Repetir los análisis exploratorios realizados en el punto 4 al dataset sin outliers. ¿Detectan algún cambio? Explicar. 
  
7) **Modelo lineal**
    a) Realizar un modelo lineal simple para explicar el **precio_en_miles** en función de las habitaciones (*rooms*) y otro modelo que explique el precio en función de la superficie total (*surface_total*).
    b) Usar la función `summary()` para obtener informacion de ambos modelos. Explicar el significado de los valores de los coeficientes estimados en cada caso. 
    c) ¿Cuál modelo usarían para predecir el precio? ¿Por qué?