---
title: "TP 2: Regresión lineal Múltiple"
output: html_notebook
---

Datos provistos por [Properati Argentina](https://www.properati.com.ar)

**Fecha y hora de entrega**: 9 de noviembre de 2020 a las 9 a.m

**Fecha y hora de devolución general**: 14 de noviembre de 2020 a las 9 a.m

## INSTRUCCIONES

Deberán realizar el trabajo en un **RNotebook** y entregarlo en formato HTML.

El **RNotebook** debe:

* Tener el siguiente nombre: eea2020_tp2_(apellido)_(nombre)
* Mostrar todo el código que escriban. NO USAR `echo=FALSE`
* Ser ordenado de acuerdo a las consignas propuestas

Una vez terminado el notebook deberán enviarlo por mail a eea.uba@gmail.com, según se indica en la guía de procedimiento.

## CRITERIOS DE EVALUACION

* Explicar los procedimientos y decisiones en el texto
* Comentar el código
* Llegar a los resultados esperados
* Recomendamos fuertemente usar las funciones de `tidyverse`

## DATOS

Se trabajará sobre un nuevo dataset de precios de inmuebles de Properati ya filtrado, que a su vez se encuentra particionado en subconjuntos de training y test. En cada consigna se indica cuál deberán usar. 

## CONSIGNAS

### 1) **Preparación de datos**

Cargar el **dataset de training** y realizar una breve descripción del mismo.

### 2) **Modelo Regresión lineal múltiple**

Utilizando el **dataset de training**:

  a) Crear un modelo para predecir el precio con todas las covariables.
  
  b) Analizar los resultados del modelo:
      i) Interpretación de los coeficientes estimados
      ii) ¿Qué observan respecto de la significatividad de las variables dummy?
      iii) Medidas de evaluación del modelo

  c) Realizar un modelo sin la covariable `l3` e interpretar sus resultados (todas las partes de la salida que consideren relevantes).

  d) ¿Cuál es el modelo que mejor explica la variabilidad del precio?

### 3) **Creación de variables**

Utilizando el **dataset de training**:

  a) En el ejercicio anterior deberían haber encontrado que algunos barrios son significativos, aunque no todos. Crear una nueva variable `barrios` que permita agrupar a los barrios. Explicar el análisis exploratorio para definir la nueva variable y los criterios utilizados en la construcción de la misma.
  
  Un **criterio sugerido** es agrupar los barrios según el precio por metro cuadrado promedio de las propiedades ubicadas en ellos, creando grupos de 'precio_alto', 'precio_medio' y 'precio_bajo'.
    
  b) Calcular el modelo que predice el precio en función de las nuevas covariables e interpretar sus resultados (todas las partes de la salida que consideren relevantes).
  
  c) ¿Qué modelo explica mejor la variabilidad de los datos, el que utiliza la variable `l3` o el que utiliza `barrio`? En su opinión, ¿Qué modelo es más útil? ¿Porqué? 
  
  d) La interpretación de los coeficientes de las variables `surface_covered` y `surface_total` puede ser un poco problemática ya que se encuentran altamente correlacionadas. Entonces, podemos construir una nueva variable `sup_descubierta` para la diferencia entre ambas superficies. Calcular nuevamente el modelo lineal del punto 3.b) (modelo con variable barrio) para todas las covariables previas (excepto `surface_total`), incluyendo `surface_covered` y `sup_descubierta` e interpretar los coeficientes de estas dos últimas variables.

### 4) **Diagnóstico del modelo**

Utilizando el **dataset de training**:

Analizar los residuos del modelo elaborado en el punto 3.d) y evaluar el cumplimiento de los supuestos del modelo lineal.

### 5) **Modelo Log(price)**

Utilizando el **dataset de training**:

Crear un modelo para log(price) e interpretar los parámetros estimados de este nuevo modelo. Comparar la performance del modelo de 3.d) con éste, tanto en términos de la variabilidad explicada como del cumplimiento de los supuestos del modelo lineal. 

$$
log(price) = \beta_0 + \beta_1log(rooms) + \beta_2log(bathrooms) + \beta_3log(surface\_covered) + \beta_4property\_type + \beta_5barrio + \beta_6surface\_patio
$$

- Les recomendamos tomar como referencia para la interpretación de los parámetros de este modelo el siguiente recorte: [Wooldridge, J. M. (2006). Introducción a la econometría: un enfoque moderno. Editorial Paraninfo.](https://github.com/eea-uba/EEA-2020/blob/master/trabajos_practicos/TP-2/Wooldrige.pdf)

### 6) **Selección de modelo**

Ahora debe elegir el mejor modelo para predecir los precios de nuevas propiedades.

Utilizando el **dataset de training** desarrollar 2 (dos) modelos de regresión múltiple nuevos. Elegir 2 (dos) modelos de los 5 (cinco) que ya fueron creados:

- modelo con todas las covariables

- modelo sin l3

- modelo con la variable *barrio*

- modelo con la variable *sup_descubierta*

- modelo con logaritmo. 

Puede elegir por los criterios que considere adecuados: métricas, facilidad de interpretación, etc. siempre y cuando los explique claramente

Evalue estos 4 (cuatro) modelos en términos de su **capacidad predictiva** en el **dataset de training**, fundamentando claramente su elección con la/s métrica/s que considere adecuada/s.

Predecir los valores de precios de las propiedades en el **dataset de testing** (recuerden que deben realizar las mismas transformaciones que hicieron en el set de training) y comparar la performance de los modelos seleccionados con la/s métrica/s elegidas previamente. Determinar con cuál modelo se queda y por qué.
