library(tidyverse)
library(modelr)
set.seed(1992)
df = readRDS("ar_properties.rds")
train_test <- df %>% resample_partition(c(train=0.7,test=0.3))
train = train_test$train %>% as_tibble()
test = train_test$test %>% as_tibble()

write_csv(x = train, "ar_properties_train.csv")
write_csv(x = test, "ar_properties_test.csv")